spring.application.name=report
server.port=8080
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/intelligence_detection_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=sjt
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#spring.ai.openai.api-key=${OPENAI_API_KEY}
#spring.ai.chat.client.enabled=true
#
#spring.elasticsearch.uris=${ES_SERVER_URL}
#spring.elasticsearch.username=${ES_USERNAME}
#spring.elasticsearch.password=${ES_PASSWORD}
#spring.ai.vectorstore.elasticsearch.initialize-schema=true

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.init.pull-model-strategy=never
spring.ai.ollama.chat.model=deepseek-r1:1.5b
spring.ai.ollama.embedding.model=bge-m3:latest
spring.ai.chat.client.enabled=true

spring.elasticsearch.uris=https://49772ea9.r33.cpolar.top
#spring.elasticsearch.username=${ES_USERNAME}
#spring.elasticsearch.password=${ES_PASSWORD}
spring.ai.vectorstore.elasticsearch.initialize-schema=true
spring.ai.vectorstore.elasticsearch.dimensions=1024