CREATE DATABASE IF NOT EXISTS smart_assistant DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE smart_assistant;

CREATE TABLE IF NOT EXISTS runs (
  id CHAR(36) PRIMARY KEY,
  prompt TEXT NOT NULL,
  status VARCHAR(32) NOT NULL,
  plan_json JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tasks (
  id CHAR(36) PRIMARY KEY,
  run_id CHAR(36) NOT NULL,
  seq INT NOT NULL,
  task_name VARCHAR(255) NOT NULL,
  task_type VARCHAR(64) NOT NULL,
  depends_on_json JSON NULL,
  status VARCHAR(32) NOT NULL,
  input_json JSON NULL,
  output_json JSON NULL,
  error TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_tasks_run_id (run_id),
  CONSTRAINT fk_tasks_run FOREIGN KEY (run_id) REFERENCES runs(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS artifacts (
  id CHAR(36) PRIMARY KEY,
  run_id CHAR(36) NOT NULL,
  kind VARCHAR(64) NOT NULL,
  name VARCHAR(255) NOT NULL,
  content MEDIUMTEXT NOT NULL,
  content_type VARCHAR(64) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_artifacts_run_id (run_id),
  CONSTRAINT fk_artifacts_run FOREIGN KEY (run_id) REFERENCES runs(id) ON DELETE CASCADE
);

